/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * ContextMenu.java
 *
 * Created on 20-nov-2013, 22:55:41
 */
package hypergraph.navigationSupport;
import hypergraph.applications.hexplorer.GraphPanel;
import javax.swing.JFrame;
import javax.swing.JPopupMenu;

/**
 *
 * @author Jesus
 */
public class ContextMenu extends javax.swing.JPanel {

    RelationsFilterPanel relpanel;
    JFrame j;
    
    /** Creates new form ContextMenu */
    public ContextMenu() {
        
        initComponents();
        
        j = new JFrame();
    }
    
    public JPopupMenu getPopup(){
        return popupMenu;
    }
    
    public void filterRelations(String str_relations){
        relpanel.startFilter(str_relations);
        
    }
    
    public JFrame getFrame(){
        
        return j;
    }
    
    public RelationsFilterPanel getRelationFilterPanel(){
        
        return relpanel;
    }
    
    public void setRelationFilterPanel(RelationsFilterPanel relationPanel){
       relpanel = relationPanel;
       relpanel.setJFrame(j);
        
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        popupMenu = new javax.swing.JPopupMenu();
        relationsEdit = new javax.swing.JMenuItem();

        relationsEdit.setText("Seleccionar relaciones");
        relationsEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                relationsEditActionPerformed(evt);
            }
        });
        popupMenu.add(relationsEdit);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

private void relationsEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_relationsEditActionPerformed
    
    j.getContentPane().add(relpanel);
    j.setBounds(400,300,485,370);
    j.setVisible(true);
    
}//GEN-LAST:event_relationsEditActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPopupMenu popupMenu;
    private javax.swing.JMenuItem relationsEdit;
    // End of variables declaration//GEN-END:variables
}
