
/*
 * PanelActivaEdicion.java
 *
 * Created on 28/03/2009, 20:23:21
 */

package hypergraph.navigationSupport;

import hypergraph.applications.hexplorer.GraphPanel;
import hypergraph.applications.hexplorer.HExplorerApplet;
import hypergraph.visualnet.TreeLayout;
import java.awt.Cursor;

/**
 *
 * @author J. Marcos
 */
public class ExtendPanel extends javax.swing.JPanel {

    private HExplorerApplet applet;
    private ExtendFrame jfa;
    private GraphPanel gp;

    /** Creates new form PanelActivaEdicion */
    public ExtendPanel(HExplorerApplet applet, GraphPanel gp) {
        
        this.applet = applet;
        this.gp = gp;
        initComponents();
        setBounds(0, 0, 90, 40);
        setVisible(true);
        this.repaint();
        
    }

    // contrae la vista del panel
    public void shrink() {
        
        GraphPanel gp = applet.getGraphPanel();
        applet.getContentPane().add(gp);
        setBounds(0, 0, 90, 40);
        TreeLayout t = (TreeLayout) applet.graphPanel.getGraphLayout();
        t.setDefaultSize(0.9);
        t.invalidate();
        this.jButtonAmpliar.setText(" Ampliar");
        applet.graphPanel.centerRootNode();       
        applet.graphPanel.repaint();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonAmpliar = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(null);

        jButtonAmpliar.setBackground(new java.awt.Color(255, 255, 255));
        jButtonAmpliar.setForeground(java.awt.Color.gray);
        jButtonAmpliar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hypergraph/navigationSupport/images/ampliar.gif"))); // NOI18N
        jButtonAmpliar.setText(" Ampliar");
        jButtonAmpliar.setBorder(javax.swing.BorderFactory.createLineBorder(java.awt.Color.lightGray));
        jButtonAmpliar.setFocusable(false);
        jButtonAmpliar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButtonAmpliarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButtonAmpliarMouseExited(evt);
            }
        });
        jButtonAmpliar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAmpliarActionPerformed(evt);
            }
        });
        add(jButtonAmpliar);
        jButtonAmpliar.setBounds(10, 10, 80, 23);
    }// </editor-fold>//GEN-END:initComponents


    private void jButtonAmpliarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAmpliarActionPerformed
        
       
        
        if (this.jButtonAmpliar.getText().equals(" Ampliar")){
            
            TreeLayout t = (TreeLayout) applet.graphPanel.getGraphLayout();
            t.setDefaultSize(0.6);
            t.invalidate();
            this.jButtonAmpliar.setText(" Reducir");
            setBounds(0, 0, 90, 40);
            applet.graphPanel.centerRootNode();    
            gp.repaint();
            jfa = new ExtendFrame(applet,this);
        } 
        else {
            shrink();
            jfa.dispose();
        }
}//GEN-LAST:event_jButtonAmpliarActionPerformed

    private void jButtonAmpliarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonAmpliarMouseEntered
        this.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_jButtonAmpliarMouseEntered

    private void jButtonAmpliarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonAmpliarMouseExited
        this.setCursor(Cursor.getPredefinedCursor(Cursor.DEFAULT_CURSOR));
    }//GEN-LAST:event_jButtonAmpliarMouseExited


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAmpliar;
    // End of variables declaration//GEN-END:variables

}
